### ISSUE TITLE
Problem: Get support page issue tracker info is out-of-date

### ISSUE THREAD

**Issue by djjuhasz** [archivematica/Issues#1261]
**Version of the documentation**

Latest [2020-07-10]

**Page (and section, if applicable) where the issue occurs**

https://www.archivematica.org/en/community/support/ "Community" section

**Description of the issue**

There is a "Redmine issue tracker" section that links to Redmine for bug and release information.

**Suggested fix**

Users should be referred to the Github Issues repo for bug and release information.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
