### ISSUE TITLE
Problem: some links in the docs are outdated as of Nov 2023

### ISSUE THREAD

**Issue by eviau-artefactual** [archivematica/Issues#1638]
**Version of the documentation**

1.15

**Page (and section, if applicable) where the issue occurs**

The documentation in general - see the appendix for a list of links to fix.

**Description of the issue**

Using Sphinx linkchecker by running `make linkcheck` in the repo, I was able to identify a few links that don't resolve and aren't redirected to anywhere. See the appendix for the complete list.

**Suggested fix**

Some of them are probably typos or are missing a `www.` ... some others might require searching a bit... I can get started and update with comments and PRs as needed.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

----

## Appendix - list of links

- [x] (admin-manual/installation-setup/installation/installation: line    1) broken    https://github.com/artefactual/archivematica/tree/qa/1.x/hack#docker-and-mac - Anchor 'docker-and-mac' not found --- see https://github.com/archivematica/Issues/issues/1646
- [x] (admin-manual/installation-setup/installation/installation: line    1) broken    https://github.com/artefactual/archivematica/tree/qa/1.x/hack#docker-and-linux - Anchor 'docker-and-linux' not found --- see https://github.com/archivematica/Issues/issues/1646
- [x] (getting-started/overview/external-tools: line  130) broken    https://pkgs.org/download/nfs-common - 402 Client Error: Payment Required for url: https://pkgs.org/download/nfs-common : **should it be https://packages.ubuntu.com/jammy/nfs-common ?** --- see https://github.com/archivematica/Issues/issues/1648
- [x] (getting-started/overview/external-tools: line  164) broken    https://opensource.org/licenses/cpl1.0.php - 404 Client Error: Not Found for url: https://opensource.org/licenses/cpl1.0.php --- see https://github.com/artefactual/archivematica-docs/pull/433/commits/6211157fc32e11f213062d61a704e616a8864609
- [x] (admin-manual/installation-setup/customization/scaling-archivematica: line   99) broken    https://raw.githubusercontent.com/artefactual-labs/am-packbuild/qa/1.x/rpm/archivematica/etc/archivematica-mcp-client.service - 404 Client Error: Not Found for url: https://raw.githubusercontent.com/artefactual-labs/am-packbuild/qa/1.x/rpm/archivematica/etc/archivematica-mcp-client.service --- see https://github.com/archivematica/Issues/issues/1649
- [x] (admin-manual/installation-setup/customization/dashboard-config: line  298) broken    www.accesstomemory.org -  **I think the https:// is missing**
- [x] (admin-manual/installation-setup/customization/antivirus-admin: line   98) broken    https://bugzilla.clamav.net/show_bug.cgi?id=11958 - HTTPSConnectionPool(host='bugzilla.clamav.net', port=443): Max retries exceeded with url: /show_bug.cgi?id=11958 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1807abacb0>, 'Connection to bugzilla.clamav.net timed out. (connect timeout=None)')) - see https://github.com/archivematica/Issues/issues/1645
- [x] (admin-manual/installation-setup/integrations/integrations: line   51) broken    https://wiki.dlib.indiana.edu/display/VarVideo/Archivematica+for+Avalon - HTTPSConnectionPool(host='wiki.dlib.indiana.edu', port=443): Max retries exceeded with url: /display/VarVideo/Archivematica+for+Avalon (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1807684a60>, 'Connection to wiki.dlib.indiana.edu timed out. (connect timeout=None)')) --- see https://github.com/artefactual/archivematica-docs/pull/433/commits/1b6d3e7621fae22b0caf75b0e8008358f590a9f6
- [x] #1650
- [x] #1651

There are a few others but although Sphinx report them as broken, the links returned valid content when I clicked on them - I am not adding them to this list.

**Comment by eviau-artefactual** [comment]
I think the other links will require a bit of detective work to find the adequate replacement... I will do my best, and might update this issue with questions in the next few days.

**Comment by eviau-artefactual** [comment]
Not sure why/how I closed this. I am confused.

**Comment by eviau-artefactual** [comment]
Current status: I am updating the links that can be updated in the PR 433 - if some more discussion is needed, I am going to link relevant Issues-PRs.

It might be a bit confusing but we will figure it out :)

**Comment by eviau-artefactual** [comment]
This should be the remaining link to be fixed, judging from the state of PRs and Issues and the job that just ran - https://github.com/artefactual/archivematica-docs/actions/runs/7992620973/job/21826539107 : 

- (getting-started/overview/external-tools: line  148) broken    https://linux.die.net/man/1/rsync - 403 Client Error: Forbidden for url: https://linux.die.net/man/1/rsync

**Comment by eviau-artefactual** [comment]
Related: https://github.com/archivematica/Issues/issues/1647

**Comment by eviau-artefactual** [comment]
And to help us find failing URLs in the future, we will merge this PR (https://github.com/artefactual/archivematica-docs/pull/439) to solve this issue( https://github.com/archivematica/Issues/issues/708) 

Currently Gearman.org isn't resolving and we believe it is only temporary: https://github.com/artefactual/archivematica-docs/pull/452

**Comment by eviau-artefactual** [comment]
There are no currently outdated links in 1.15 :sparkles: 

Closing this issue.
