### ISSUE TITLE
Problem: selecting files to arrange into a SIP on the Appraisal tab is only possible by drag-n-drop one file at a time.

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#369]
**Expected behaviour**
Using the tagging feature on the Appraisal tab, make it possible to tag-n-click, i.e. all files with the same tag are included in a SIP at the click of a button.

If this were to be integrated into the existing Archivematica Appraisal user interface it might look like this:

![screen shot 2019-01-24 at 13 26 55](https://user-images.githubusercontent.com/672121/51710528-5887b400-1fde-11e9-8087-28d701321846.png)

![screen shot 2019-01-24 at 13 33 59](https://user-images.githubusercontent.com/672121/51710533-5b82a480-1fde-11e9-8db8-9ac180824362.png)

![screen shot 2019-01-28 at 15 09 29](https://user-images.githubusercontent.com/672121/51933884-2cda4480-23b7-11e9-8341-aaaafd2f706c.png)

Acceptance criteria:

- [x] Add buttons to remove individual tags from files and folders in the Backlog pane. The tag changes should update the File list and Arrangement panes as well
- [x] Add a Tag dropdown to the Arrangement pane that creates a new SIP directory (named after the tag). The files in the Arrangement pane will copy the hierarchical structure of the directories and files in the Backlog pane
- [x] Add a Create SIP button next to the new Tag dropdown that instigates the “Approve SIP Creation” microservice on the Archivematica Ingest tab 

**Current behaviour**

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

parent of #472 
parent of #507
