### ISSUE TITLE
 Problem: workflow data has inconsistencies

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#45]
This is an epic to keep track of a number of consistency issues in our workflow data.

Dependencies:
- [x] Parent of https://github.com/archivematica/Issues/issues/142 (orphan mscl)
- [x] Parent of https://github.com/artefactual/archivematica/issues/1090 (job after file id fails)
- [ ] Parent of https://github.com/artefactual/archivematica/issues/598 (quarantine delay is unreliable)
- [ ] Parent of https://github.com/artefactual/archivematica/issues/677 (unused watched dirs)
- [ ] Parent of https://github.com/artefactual/archivematica/issues/784 (undefined exits)
- [ ] Parent of https://github.com/archivematica/Issues/issues/77 (archivematicaFITS)
- [ ] backupDIP client script is not used?
- [ ] Delete unused chains (amflow can tell you which)
- [ ] Delete orphan link `eb52299b-9ae6-4a1f-831e-c7eee0de829f`

Also related: https://github.com/artefactual/archivematica/issues/1101 (translations of workflows).

**Comment by ross-spencer** [comment]
Related https://github.com/archivematica/Issues/issues/347 (might indicate other inconsistencies)
Related https://github.com/archivematica/Issues/issues/298 (looks like a possible wontfix, but mightfix) 
Related https://github.com/artefactual/archivematica/issues/837 (unneeded files not executed for unzipped bags)
Related https://github.com/archivematica/Issues/issues/426 (DSpace quarantine issue)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
